{{- if not .Values.nginx.configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlas.nginx.configmap" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
data:
  {{ .Values.nginx.configKey }}: |
{{ (.Files.Get "scripts/deployment/helm/atlas/nginx/default.conf" ) | indent 4 }}
{{- end }}
