apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atlas.svc.nginx" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.replicaCount.nginx }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: nginx
  template:
    metadata:
      labels:
        {{- include "atlas.labels" . | nindent 8 }}
        component: nginx
    spec:
      serviceAccountName: {{ default (include "atlas.fullname" .) .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.pod.securityContext | nindent 8 }}
      containers:
        - name: nginx
          image: "{{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}"
          imagePullPolicy: {{ .Values.images.nginx.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.nginx.port }}
              name: http
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "atlas.svc.nginx" . }}-conf
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
