{{- if and .Values.minio.enabled .Values.minio.persistence.enabled (not .Values.minio.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "atlas.svc.minio" . }}-pvc
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  {{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  {{- end }}
{{- end }}
