{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "atlas.svc.nginx" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "atlas.svc.nginx" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
