{{- if and .Values.imagePullSecret.create .Values.imagePullSecret.username .Values.imagePullSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.imagePullSecret.registry }}": {
          "username": "{{ .Values.imagePullSecret.username }}",
          "password": "{{ .Values.imagePullSecret.password }}",
          "email": "{{ .Values.imagePullSecret.email }}",
          "auth": "{{ printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.password | b64enc }}"
        }
      }
    }
{{- end }}
