apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlas.svc.main" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
    component: main-app
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: main-app
  ports:
    - name: http
      port: {{ .Values.service.mainApp.port }}
      targetPort: http
  type: ClusterIP
