apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlas.svc.nginx" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
    component: nginx
  {{- with .Values.nginx.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: nginx
  ports:
    - name: http
      port: {{ .Values.service.nginx.port }}
      targetPort: http
  type: {{ .Values.service.nginx.type }}
